export const testWords = [
  {
    id: '5e9f5ee35eb9e72bc21af98c',
    group: 2,
    page: 3,
    word: 'alley',
    image: 'files/04_1261.jpg',
    audio: 'files/04_1261.mp3',
    audioMeaning: 'files/04_1261_meaning.mp3',
    audioExample: 'files/04_1261_example.mp3',
    textMeaning: 'An <i>alley</i> is a narrow road between houses or buildings.',
    textExample: 'The <b>alley</b> behind my house looks dirty.',
    transcription: '[ǽli]',
    textExampleTranslate: 'Аллея позади моего дома выглядит грязной',
    textMeaningTranslate: 'Аллея - это узкая дорога между домами или зданиями',
    wordTranslate: 'аллея',
  },
  {
    id: '5e9f5ee35eb9e72bc21af98d',
    group: 2,
    page: 3,
    word: 'bunch',
    image: 'files/04_1263.jpg',
    audio: 'files/04_1263.mp3',
    audioMeaning: 'files/04_1263_meaning.mp3',
    audioExample: 'files/04_1263_example.mp3',
    textMeaning: 'A <i>bunch</i> is a group of the same things.',
    textExample: 'She was hungry, so she ate the entire <b>bunch</b> of grapes.',
    transcription: '[bʌntʃ]',
    textExampleTranslate: 'Она была голодна, поэтому съела всю гроздь винограда',
    textMeaningTranslate: 'Связка - это группа одинаковых вещей',
    wordTranslate: 'связка',
  },
  {
    id: '5e9f5ee35eb9e72bc21af98e',
    group: 2,
    page: 3,
    word: 'ax',
    image: 'files/04_1262.jpg',
    audio: 'files/04_1262.mp3',
    audioMeaning: 'files/04_1262_meaning.mp3',
    audioExample: 'files/04_1262_example.mp3',
    textMeaning: 'An <i>ax</i> is a tool used to cut wood.',
    textExample: 'She used an <b>ax</b> to cut some wood for the fire.',
    transcription: '[æks]',
    textExampleTranslate: 'Она использовала топор, чтобы срубить дрова для огня',
    textMeaningTranslate: 'Топор - это инструмент, используемый для резки дерева',
    wordTranslate: 'топор',
  },
  {
    id: '5e9f5ee35eb9e72bc21af98f',
    group: 2,
    page: 3,
    word: 'chore',
    image: 'files/04_1264.jpg',
    audio: 'files/04_1264.mp3',
    audioMeaning: 'files/04_1264_meaning.mp3',
    audioExample: 'files/04_1264_example.mp3',
    textMeaning: 'A <i>chore</i> is an unpleasant job that must be done.',
    textExample: 'It’s Nikki’s <b>chore</b> to do the dishes every Tuesday and Wednesday night.',
    transcription: '[tʃɔːr]',
    textExampleTranslate: 'Это работа Никки, чтобы мыть посуду каждый вторник и среду вечером',
    textMeaningTranslate: 'Работа по дому - неприятная работа, которую нужно выполнить',
    wordTranslate: 'рутина',
  },
  {
    id: '5e9f5ee35eb9e72bc21af990',
    group: 2,
    page: 3,
    word: 'decent',
    image: 'files/04_1265.jpg',
    audio: 'files/04_1265.mp3',
    audioMeaning: 'files/04_1265_meaning.mp3',
    audioExample: 'files/04_1265_example.mp3',
    textMeaning: 'A <i>decent</i> person or thing is OK or good enough.',
    textExample: 'Eric did a <b>decent</b> job painting the fence.',
    transcription: '[díːsənt]',
    textExampleTranslate: 'Эрик проделал достойную работу, покрасив забор',
    textMeaningTranslate: 'Приличный человек или вещь в порядке или достаточно хороши',
    wordTranslate: 'приличный',
  },
  {
    id: '5e9f5ee35eb9e72bc21af991',
    group: 2,
    page: 3,
    word: 'disgraceful',
    image: 'files/04_1266.jpg',
    audio: 'files/04_1266.mp3',
    audioMeaning: 'files/04_1266_meaning.mp3',
    audioExample: 'files/04_1266_example.mp3',
    textMeaning: '<i>Disgraceful</i> behavior is behavior that is very bad.',
    textExample: 'This is a <b>disgraceful</b> waste of money.',
    transcription: '[disgréisful]',
    textExampleTranslate: 'Это позорная трата денег',
    textMeaningTranslate: 'Позорное поведение - это очень плохое поведение',
    wordTranslate: 'позорно',
  },
  {
    id: '5e9f5ee35eb9e72bc21af992',
    group: 2,
    page: 3,
    word: 'grateful',
    image: 'files/04_1268.jpg',
    audio: 'files/04_1268.mp3',
    audioMeaning: 'files/04_1268_meaning.mp3',
    audioExample: 'files/04_1268_example.mp3',
    textMeaning: 'A <i>grateful</i> person feels thankful about something.',
    textExample: 'The girls were <b>grateful</b> for the chance to visit their grandfather.',
    transcription: '[gréitfəl]',
    textExampleTranslate: 'Девушки были благодарны за возможность навестить дедушку',
    textMeaningTranslate: 'Благодарный человек чувствует себя благодарным за что-то',
    wordTranslate: 'благодарен',
  },
  {
    id: '5e9f5ee35eb9e72bc21af993',
    group: 2,
    page: 3,
    word: 'elbow',
    image: 'files/04_1267.jpg',
    audio: 'files/04_1267.mp3',
    audioMeaning: 'files/04_1267_meaning.mp3',
    audioExample: 'files/04_1267_example.mp3',
    textMeaning: 'The <i>elbow</i> is the middle part of an arm, where it bends.',
    textExample: 'She pointed to her <b>elbow</b> to show me where she hurt herself.',
    transcription: '[élbou]',
    textExampleTranslate: 'Она указала на свой локоть, чтобы показать мне, где она поранилась',
    textMeaningTranslate: 'Локоть - это средняя часть руки, где он сгибается',
    wordTranslate: 'локоть',
  },
  {
    id: '5e9f5ee35eb9e72bc21af994',
    group: 2,
    page: 3,
    word: 'irritate',
    image: 'files/04_1269.jpg',
    audio: 'files/04_1269.mp3',
    audioMeaning: 'files/04_1269_meaning.mp3',
    audioExample: 'files/04_1269_example.mp3',
    textMeaning: 'To <i>irritate</i> means to annoy someone.',
    textExample: 'She was&nbsp;<b>irritated</b>&nbsp;when her brother told her that he had lost her camera.',
    transcription: '[írətèit]',
    textExampleTranslate: 'Она была раздражена, когда ее брат сказал ей, что он потерял ее камеру',
    textMeaningTranslate: 'Раздражать - значит раздражать кого-то',
    wordTranslate: 'раздражать',
  },
  {
    id: '5e9f5ee35eb9e72bc21af995',
    group: 2,
    page: 3,
    word: 'kid',
    image: 'files/04_1270.jpg',
    audio: 'files/04_1270.mp3',
    audioMeaning: 'files/04_1270_meaning.mp3',
    audioExample: 'files/04_1270_example.mp3',
    textMeaning: 'To <i>kid</i> is to say something that is not true as a joke.',
    textExample: 'I am not really mad. I was <b>kidding</b> when I said I was angry.',
    transcription: '[kid]',
    textExampleTranslate: 'Я на самом деле не злюсь. Я пошутил, когда сказал, что злюсь',
    textMeaningTranslate: 'Для ребенка значит сказать что-то, что не является правдой в шутку',
    wordTranslate: 'дитя',
  },
  {
    id: '5e9f5ee35eb9e72bc21af996',
    group: 2,
    page: 3,
    word: 'loose',
    image: 'files/04_1271.jpg',
    audio: 'files/04_1271.mp3',
    audioMeaning: 'files/04_1271_meaning.mp3',
    audioExample: 'files/04_1271_example.mp3',
    textMeaning: 'A <i>loose</i> thing is not held in place tightly.',
    textExample: 'The bolt was <b>loose</b>, so I tightened it with the wrench.',
    transcription: '[luːs]',
    textExampleTranslate: 'Болт был ослаблен, поэтому я затянул его гаечным ключом',
    textMeaningTranslate: 'Свободная вещь не держится на месте крепко',
    wordTranslate: 'потерять',
  },
  {
    id: '5e9f5ee35eb9e72bc21af997',
    group: 2,
    page: 3,
    word: 'offend',
    image: 'files/04_1272.jpg',
    audio: 'files/04_1272.mp3',
    audioMeaning: 'files/04_1272_meaning.mp3',
    audioExample: 'files/04_1272_example.mp3',
    textMeaning: 'To <i>offend</i> is to make someone angry or upset.',
    textExample: 'They were both <b>offended</b> by what they had said to each other.',
    transcription: '[əfénd]',
    textExampleTranslate: 'Они оба были оскорблены тем, что они сказали друг другу',
    textMeaningTranslate: 'Обидеть значит обидеть кого-то или расстроить',
    wordTranslate: 'обидеть',
  },
  {
    id: '5e9f5ee35eb9e72bc21af998',
    group: 2,
    page: 3,
    word: 'overnight',
    image: 'files/04_1273.jpg',
    audio: 'files/04_1273.mp3',
    audioMeaning: 'files/04_1273_meaning.mp3',
    audioExample: 'files/04_1273_example.mp3',
    textMeaning: 'An <i>overnight</i> action happens during the night.',
    textExample: 'The campers stayed in the tent <b>overnight</b>.',
    transcription: '[óuvərnait]',
    textExampleTranslate: 'Отдыхающие остались в палатке на ночь',
    textMeaningTranslate: 'Ночное действие происходит ночью',
    wordTranslate: 'с ночевкой',
  },
  {
    id: '5e9f5ee35eb9e72bc21af999',
    group: 2,
    page: 3,
    word: 'persist',
    image: 'files/04_1274.jpg',
    audio: 'files/04_1274.mp3',
    audioMeaning: 'files/04_1274_meaning.mp3',
    audioExample: 'files/04_1274_example.mp3',
    textMeaning: 'To <i>persist</i> means to keep doing something even when it is hard.',
    textExample: 'Even though the lesson was difficult, he <b>persisted</b> until he understood.',
    transcription: '[pərsíst]',
    textExampleTranslate: 'Хотя урок был трудным, он продолжал, пока не понял',
    textMeaningTranslate: 'Упорствовать - значит продолжать делать что-то, даже когда это трудно',
    wordTranslate: 'сохраняются',
  },
  {
    id: '5e9f5ee35eb9e72bc21af99b',
    group: 2,
    page: 3,
    word: 'scar',
    image: 'files/04_1276.jpg',
    audio: 'files/04_1276.mp3',
    audioMeaning: 'files/04_1276_meaning.mp3',
    audioExample: 'files/04_1276_example.mp3',
    textMeaning: 'A <i>scar</i> is a mark on the skin after a wound heals.',
    textExample: 'The man had horrible <b>scars</b> on his cheek and forehead.',
    transcription: '[skɑːr]',
    textExampleTranslate: 'У человека были ужасные шрамы на щеке и лбу',
    textMeaningTranslate: 'Рубец - это след на коже после заживления раны',
    wordTranslate: 'шрам',
  },
  {
    id: '5e9f5ee35eb9e72bc21af99a',
    group: 2,
    page: 3,
    word: 'pine',
    image: 'files/04_1275.jpg',
    audio: 'files/04_1275.mp3',
    audioMeaning: 'files/04_1275_meaning.mp3',
    audioExample: 'files/04_1275_example.mp3',
    textMeaning: 'A <i>pine</i> is a type of tall, thin tree with needles instead of leaves.',
    textExample: 'There were many beautiful <b>pine</b> trees in the forest.',
    transcription: '[pain]',
    textExampleTranslate: 'В лесу было много прекрасных сосен',
    textMeaningTranslate: 'Сосна - это тип высокого, тонкого дерева с иголками вместо листьев',
    wordTranslate: 'сосна',
  },
  {
    id: '5e9f5ee35eb9e72bc21af99c',
    group: 2,
    page: 3,
    word: 'sensation',
    image: 'files/04_1277.jpg',
    audio: 'files/04_1277.mp3',
    audioMeaning: 'files/04_1277_meaning.mp3',
    audioExample: 'files/04_1277_example.mp3',
    textMeaning: 'A <i>sensation</i> is a feeling that people get from their senses.',
    textExample: 'Mom got a painful <b>sensation</b> in her head from the loud noise.',
    transcription: '[senséiʃən]',
    textExampleTranslate: 'Мама получила болезненное ощущение в голове от громкого шума',
    textMeaningTranslate: 'Сенсация - это чувство, которое люди получают от своих чувств',
    wordTranslate: 'ощущение',
  },
  {
    id: '5e9f5ee35eb9e72bc21af99d',
    group: 2,
    page: 3,
    word: 'sled',
    image: 'files/04_1278.jpg',
    audio: 'files/04_1278.mp3',
    audioMeaning: 'files/04_1278_meaning.mp3',
    audioExample: 'files/04_1278_example.mp3',
    textMeaning: 'A <i>sled</i> is a small vehicle used on snow.',
    textExample: 'Marvin likes to ride his <b>sled</b> down the hill in winter.',
    transcription: '[sled]',
    textExampleTranslate: 'Марвин любит кататься на санках зимой вниз по склону',
    textMeaningTranslate: 'Сани - это маленький автомобиль, используемый на снегу',
    wordTranslate: 'санки',
  },
  {
    id: '5e9f5ee35eb9e72bc21af99e',
    group: 2,
    page: 3,
    word: 'tease',
    image: 'files/04_1279.jpg',
    audio: 'files/04_1279.mp3',
    audioMeaning: 'files/04_1279_meaning.mp3',
    audioExample: 'files/04_1279_example.mp3',
    textMeaning: 'To <i>tease</i> means to laugh at or make fun of someone.',
    textExample: 'Jake <b>teased</b> Charlie because he was the new student.',
    transcription: '[tiːz]',
    textExampleTranslate: 'Джейк дразнил Чарли, потому что он был новым учеником',
    textMeaningTranslate: 'Дразнить означает смеяться или смеяться над кем-то',
    wordTranslate: 'дразнить',
  },
  {
    id: '5e9f5ee35eb9e72bc21af99f',
    group: 2,
    page: 3,
    word: 'valentine',
    image: 'files/04_1280.jpg',
    audio: 'files/04_1280.mp3',
    audioMeaning: 'files/04_1280_meaning.mp3',
    audioExample: 'files/04_1280_example.mp3',
    textMeaning: 'A <i>valentine</i> is someone loved or admired with great affection.',
    textExample: 'Harry wanted Molly to be his <b>valentine</b>.',
    transcription: '[vǽləntàin]',
    textExampleTranslate: 'Гарри хотел, чтобы Молли была его валентинкой',
    textMeaningTranslate: 'Валентина - это тот, кого любят или восхищают с большой любовью',
    wordTranslate: 'валентин',
  },
];

